repos:
  -   repo: https://github.com/PyCQA/flake8
      rev: '7.0.0'  # Use the latest version
      hooks:
      -   id: flake8
          args: ['--max-line-length', '100']  # Specify additional arguments
          files: ^.*\.py$  # Only run on Python files
          exclude: '^vendor/'  # Exclude files or directories

  -   repo: https://github.com/psf/black
      rev: '23.12.1'  # Use the latest version
      hooks:
      -   id: black
          args: ['--line-length', '100']  # Specify line length

  -   repo: https://github.com/pre-commit/mirrors-eslint
      rev: 'v9.0.0-alpha.0'  # Use the latest version
      hooks:
      -   id: eslint
          additional_dependencies: ['eslint-plugin-react']
          args: ['--max-warnings', '0']  # Fail if there are warnings
